-- AlterTable
ALTER TABLE "Bookshelf" ADD COLUMN     "lastReadAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "listenPercent" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "listenPosition" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "readPercent" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "readPosition" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "speed" DOUBLE PRECISION NOT NULL DEFAULT 1.0;
